# Use the official lightweight Node.js 14 image as base
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose port 3000 to the outside world
EXPOSE 8080

# Start the React development server
CMD ["npm", "run", "dev"]
